### Tallenna token: klikkaa "Send Request", kopioi vastauksen "token"-arvo alle @token-muuttujaan
POST http://localhost:3003/api/login
Content-Type: application/json
Authorization: Bearer <token>

{

  "username": "mutkanen2",
  "password": "salainen2"
}